name: 'Codecov Test Result Action'
description: 'GitHub Action that uploads test result reports for your repository to codecov.io'
author: 'Codecov'
inputs:
  token:
    description: 'Token used to access Github API. Takes value of github.token by default.'
    required: false
    default: ${{ github.token }}
  directory:
    description: 'Directory to search for test result reports.'
    required: false
  disable_search:
    description: 'Disable search for test result files. This is helpful when specifying what files you want to upload with the --file option.'
    required: false
  exclude:
    description: 'Folders to exclude from search'
    required: false
  fail_ci_if_error:
    description: 'Specify whether or not CI build should fail if Codecov runs into an error during processing'
    required: false
  file:
    description: 'Path to test result file to upload'
    required: false
  files:
    description: 'Comma-separated list of files to upload'
    required: false
  handle_no_reports_found:
    description: 'Raise no exceptions when no test result reports found'
    required: false
  os:
    description: 'Override the assumed OS. Options are linux | macos | windows.'
    required: false
  root_dir:
    description: 'Used when not in git/hg project to identify project root directory'
    required: false
  verbose:
    description: 'Specify whether the Codecov output should be verbose'
    required: false
  version:
    description: 'Specify which version of the Codecov CLI should be used. Defaults to `latest`'
    required: false
  working-directory:
    description: 'Directory in which to execute codecov.sh'
    required: false




branding:
  color: 'red'
  icon: 'umbrella'

runs:
  using: 'node20'
  main: 'dist/index.js'